#!/bin/bash

project=DrawingTest
#project=Test3D

files="
$project/core/src/io/github/dkessner/$project.java 
ProcessingGdx/src/main/java/io/github/dkessner/PApplet.java
ProcessingGdx/src/main/java/io/github/dkessner/PGraphics.java
ProcessingGdx/src/main/java/io/github/dkessner/PImage.java
"

for f in $files
do
    echo $f
done

gvim -c "set mp=runDesktop\ $project" $files

