#!/bin/bash

# DrawingTest/core/src/io/github/dkessner/DrawingTest.java 

files="
Test3D/core/src/io/github/dkessner/Test3D.java 
ProcessingGdx/src/main/java/processing/core/PApplet.java
ProcessingGdx/src/main/java/processing/core/PGraphics.java
ProcessingGdx/src/main/java/processing/core/PImage.java
"

for f in $files
do
    echo $f
done

gvim -c "set mp=runDesktop\ Test3D" $files

