#!/bin/bash
#
# runHtml
#

if [ $# -ne 1 ]
then
    echo Usage: runHtml project
    exit 1
fi

project=$1

mydir=$(dirname "$(realpath "$0")")
pushd $mydir > /dev/null

if [ ! -d $project ]
then
    $project is not a valid project directory
    exit 1
fi

pushd ProcessingGdx > /dev/null
gradlew build
if [ $? -ne 0 ]; then exit 1 ;fi
popd > /dev/null

pushd $project > /dev/null
gradlew html:clean
if [ $? -ne 0 ]; then exit 1 ;fi
gradlew html:build
if [ $? -ne 0 ]; then exit 1 ;fi
gradlew html:superDev

