//
// PImage.java
//
// Darren Kessner
//


package processing.core;


import com.badlogic.gdx.graphics.Texture;


/**
 * Represents a 2D image, either loaded from a file or generated by drawing
 * into a frame buffer.
 */
public class PImage implements PConstants
{
    public PImage() {}

    public PImage(String filename) 
    {
        texture = new Texture(filename);
        width = texture.getWidth();
        height = texture.getHeight();
        flipY = true;
    }

    @Override
    public void finalize() 
    {
        texture.dispose();
    }

    protected int width;
    protected int height;
    protected boolean flipY = false;

    // libgdx implementation

    Texture getTexture() {return texture;}
    boolean flipY() {return flipY;}

    private Texture texture;
}

